/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

CMersenneTwister *_E5();
int _E12();
CPolynomialTable *_E8();
int _E11();
void __cdecl _E9(); // idb
unsigned int __thiscall CDisplacementTable::Reflect(CDisplacementTable *__hidden this, unsigned int, unsigned __int8); // idb
void __thiscall CDisplacementTable::Randomize(CDisplacementTable *__hidden this); // idb
unsigned int __thiscall CDisplacementTable::RandomStatic(CDisplacementTable *__hidden this); // idb
unsigned int __thiscall CDisplacementTable::RandomDynamic(CDisplacementTable *__hidden this); // idb
int __thiscall CDisplacementTable::operator[](_DWORD *this, int a2);
void __thiscall CDisplacementTable::GenerateTable(CDisplacementTable *__hidden this); // idb
CDisplacementTable *__thiscall CDisplacementTable::CDisplacementTable(CDisplacementTable *__hidden this); // idb
void __thiscall CDisplacementTable::~CDisplacementTable(CDisplacementTable *__hidden this); // idb
// CMersenneTwister *__thiscall CMersenneTwister::CMersenneTwister(CMersenneTwister *__hidden this); idb
// CPolynomialTable *__thiscall CPolynomialTable::CPolynomialTable(CPolynomialTable *__hidden this); idb
// int __cdecl atexit(void (__cdecl *)());
// void __thiscall CPolynomialTable::~CPolynomialTable(CPolynomialTable *__hidden this); idb
// void __thiscall CMersenneTwister::seed(CMersenneTwister *__hidden this); idb
// unsigned int __thiscall CPolynomialTable::RandomDynamic(CPolynomialTable *__hidden this); idb
// unsigned int __thiscall CMersenneTwister::randInt(CMersenneTwister *__hidden this); idb
// void *__cdecl operator new(unsigned int); idb
// void __thiscall CPolynomialTable::GenerateTable(CPolynomialTable *__hidden this); idb
// void __cdecl operator delete(void *); idb

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN CDisplacementTable::rand; // weak
char _S10; // weak
_UNKNOWN CDisplacementTable::dwPolynomialTable; // weak


//----- (000009E8) --------------------------------------------------------
CMersenneTwister *_E5()
{
  return CMersenneTwister::CMersenneTwister((CMersenneTwister *)&CDisplacementTable::rand);
}

//----- (000009F8) --------------------------------------------------------
int _E12()
{
  _E8();
  return _E11();
}

//----- (00000A08) --------------------------------------------------------
CPolynomialTable *_E8()
{
  return CPolynomialTable::CPolynomialTable((CPolynomialTable *)&CDisplacementTable::dwPolynomialTable);
}

//----- (00000A18) --------------------------------------------------------
int _E11()
{
  return atexit(_E9);
}

//----- (00000A28) --------------------------------------------------------
void __cdecl _E9()
{
  if ( (_S10 & 1) == 0 )
  {
    _S10 |= 1u;
    CPolynomialTable::~CPolynomialTable((CPolynomialTable *)&CDisplacementTable::dwPolynomialTable);
  }
}
// 9D0: using guessed type char _S10;

//----- (00000A48) --------------------------------------------------------
unsigned int __thiscall CDisplacementTable::Reflect(CDisplacementTable *this, unsigned int a2, unsigned __int8 a3)
{
  unsigned int result; // eax
  int v4; // esi
  char v6; // cl

  result = 0;
  if ( !__OFSUB__(a3 + 1, 1) && a3 != 0 )
  {
    v4 = a3;
    v6 = a3 - 1;
    do
    {
      if ( (a2 & 1) != 0 )
        result |= 1 << v6;
      a2 >>= 1;
      --v6;
      --v4;
    }
    while ( v4 );
  }
  return result;
}

//----- (00000A88) --------------------------------------------------------
void __thiscall CDisplacementTable::Randomize(CDisplacementTable *this)
{
  CMersenneTwister::seed((CMersenneTwister *)&CDisplacementTable::rand);
}

//----- (00000A98) --------------------------------------------------------
unsigned int __thiscall CDisplacementTable::RandomStatic(CDisplacementTable *this)
{
  return CPolynomialTable::RandomDynamic((CPolynomialTable *)&CDisplacementTable::dwPolynomialTable);
}

//----- (00000AA8) --------------------------------------------------------
unsigned int __thiscall CDisplacementTable::RandomDynamic(CDisplacementTable *this)
{
  int v2; // eax
  unsigned int result; // eax

  if ( !*(_DWORD *)this )
    return 0;
  CDisplacementTable::Randomize(this);
  v2 = (unsigned __int8)CMersenneTwister::randInt((CMersenneTwister *)&CDisplacementTable::rand);
  if ( v2 <= 0 )
    result = *(_DWORD *)(*(_DWORD *)this + 4 * (v2 % 256));
  else
    result = *(_DWORD *)(*(_DWORD *)this + 4 * v2);
  return result;
}
// ACB: conditional instruction was optimized away because of 'eax.4 in (1..FF)'

//----- (00000AF8) --------------------------------------------------------
int __thiscall CDisplacementTable::operator[](_DWORD *this, int a2)
{
  int result; // eax

  if ( *this && a2 > 0 && a2 < 256 )
    result = *(_DWORD *)(*this + 4 * a2);
  else
    result = 0;
  return result;
}

//----- (00000B28) --------------------------------------------------------
void __thiscall CDisplacementTable::GenerateTable(CDisplacementTable *this)
{
  signed int i; // edi
  int v3; // ebx
  unsigned int v4; // eax

  if ( *(_DWORD *)this )
  {
    operator delete(*(void **)this);
    *(_DWORD *)this = 0;
    CPolynomialTable::GenerateTable((CPolynomialTable *)&CDisplacementTable::dwPolynomialTable);
  }
  *(_DWORD *)this = operator new(0x400u);
  for ( i = 0; i < 256; *(_DWORD *)(*(_DWORD *)this + 4 * i - 4) = v4 )
  {
    v3 = 8;
    *(_DWORD *)(*(_DWORD *)this + 4 * i) = CDisplacementTable::Reflect(this, i, 8u) << 24;
    do
    {
      --v3;
      *(_DWORD *)(*(_DWORD *)this + 4 * i) = (2 * *(_DWORD *)(*(_DWORD *)this + 4 * i)) ^ (*(int *)(*(_DWORD *)this
                                                                                                  + 4 * i) < 0 ? CDisplacementTable::RandomStatic(this) : 0);
    }
    while ( v3 );
    v4 = CDisplacementTable::Reflect(this, *(_DWORD *)(*(_DWORD *)this + 4 * i++), 0x20u);
  }
}

//----- (00000BC8) --------------------------------------------------------
CDisplacementTable *__thiscall CDisplacementTable::CDisplacementTable(CDisplacementTable *this)
{
  *(_DWORD *)this = 0;
  CDisplacementTable::GenerateTable(this);
  return this;
}

//----- (00000BE8) --------------------------------------------------------
void __thiscall CDisplacementTable::~CDisplacementTable(CDisplacementTable *this)
{
  if ( *(_DWORD *)this )
  {
    operator delete(*(void **)this);
    *(_DWORD *)this = 0;
  }
}

// nfuncs=24 queued=13 decompiled=13 lumina nreq=0 worse=0 better=0
// ALL OK, 13 function(s) have been successfully decompiled
