/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

CFileMapping *__thiscall CFileMapping::CFileMapping(CFileMapping *this);
void __thiscall CFileMapping::OpenRead(CFileMapping *__hidden this, LPCSTR lpFileName, unsigned int *, unsigned int); // idb
LPVOID __cdecl OpenFileMappingRead(LPCSTR lpFileName, int a2, SIZE_T dwNumberOfBytesToMap, int a4);
void __thiscall CFileMapping::OpenReadWrite(CFileMapping *__hidden this, LPCSTR lpFileName, unsigned int *, unsigned int); // idb
LPVOID __cdecl OpenFileMappingReadWrite(LPCSTR lpFileName, int a2, SIZE_T dwNumberOfBytesToMap, int a4);
void __thiscall CFileMapping::OpenCreate(CFileMapping *__hidden this, LPCSTR lpFileName, LONG lDistanceToMove); // idb
HANDLE __cdecl OpenFileMappingCreate(LPCSTR lpFileName, int a2, LONG lDistanceToMove);
void __thiscall CFileMapping::ReOpenCreate(CFileMapping *__hidden this, LONG lDistanceToMove); // idb
void __thiscall CFileMapping::Close(CFileMapping *__hidden this); // idb
// LPVOID __stdcall MapViewOfFile(HANDLE hFileMappingObject, DWORD dwDesiredAccess, DWORD dwFileOffsetHigh, DWORD dwFileOffsetLow, SIZE_T dwNumberOfBytesToMap);
// void __stdcall GetSystemInfo(LPSYSTEM_INFO lpSystemInfo);
// BOOL __stdcall CloseHandle(HANDLE hObject);
// HANDLE __stdcall CreateFileMappingA(HANDLE hFile, LPSECURITY_ATTRIBUTES lpFileMappingAttributes, DWORD flProtect, DWORD dwMaximumSizeHigh, DWORD dwMaximumSizeLow, LPCSTR lpName);
// DWORD __stdcall GetFileSize(HANDLE hFile, LPDWORD lpFileSizeHigh);
// HANDLE __stdcall CreateFileA(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
// BOOL __stdcall SetEndOfFile(HANDLE hFile);
// DWORD __stdcall SetFilePointer(HANDLE hFile, LONG lDistanceToMove, PLONG lpDistanceToMoveHigh, DWORD dwMoveMethod);
// BOOL __stdcall UnmapViewOfFile(LPCVOID lpBaseAddress);


//----- (00000000) --------------------------------------------------------
CFileMapping *__thiscall CFileMapping::CFileMapping(CFileMapping *this)
{
  CFileMapping *result; // eax

  result = this;
  *(_DWORD *)this = -1;
  *((_DWORD *)this + 1) = 0;
  *((_DWORD *)this + 2) = 0;
  return result;
}

//----- (00000030) --------------------------------------------------------
void __thiscall CFileMapping::OpenRead(CFileMapping *this, LPCSTR lpFileName, unsigned int *a3, unsigned int dwNumberOfBytesToMap)
{
  CFileMapping::Close(this);
  *((_DWORD *)this + 1) = OpenFileMappingRead(lpFileName, (int)a3, dwNumberOfBytesToMap, (int)this + 8);
}

//----- (00000060) --------------------------------------------------------
LPVOID __cdecl OpenFileMappingRead(LPCSTR lpFileName, int a2, SIZE_T dwNumberOfBytesToMap, int a4)
{
  HANDLE v4; // eax
  void *v5; // esi
  HANDLE v7; // ebp
  DWORD v8; // esi
  DWORD v9; // ecx
  LPVOID v10; // esi
  struct _SYSTEM_INFO SystemInfo; // [esp+Ch] [ebp-24h] BYREF

  v4 = CreateFileA(lpFileName, 0x80000000, 1u, 0, 3u, 0, 0);
  v5 = v4;
  if ( v4 == (HANDLE)-1 )
    return 0;
  if ( a4 )
    *(_DWORD *)a4 = GetFileSize(v4, 0);
  v7 = CreateFileMappingA(v5, 0, 2u, 0, 0, 0);
  CloseHandle(v5);
  if ( !v7 )
    return 0;
  v8 = 0;
  if ( a2 )
  {
    v8 = *(_DWORD *)a2;
    GetSystemInfo(&SystemInfo);
    v9 = *(_DWORD *)a2;
    if ( *(_DWORD *)a2 % SystemInfo.dwAllocationGranularity )
    {
      v8 = SystemInfo.dwAllocationGranularity * (v9 / SystemInfo.dwAllocationGranularity);
      *(_DWORD *)a2 = v8;
      dwNumberOfBytesToMap += v9 - v8;
    }
  }
  v10 = MapViewOfFile(v7, 4u, 0, v8, dwNumberOfBytesToMap);
  CloseHandle(v7);
  return v10;
}

//----- (00000130) --------------------------------------------------------
void __thiscall CFileMapping::OpenReadWrite(CFileMapping *this, LPCSTR lpFileName, unsigned int *a3, unsigned int dwNumberOfBytesToMap)
{
  CFileMapping::Close(this);
  *((_DWORD *)this + 1) = OpenFileMappingReadWrite(lpFileName, (int)a3, dwNumberOfBytesToMap, (int)this + 8);
}

//----- (00000160) --------------------------------------------------------
LPVOID __cdecl OpenFileMappingReadWrite(LPCSTR lpFileName, int a2, SIZE_T dwNumberOfBytesToMap, int a4)
{
  HANDLE v4; // eax
  void *v5; // esi
  HANDLE v7; // ebp
  DWORD v8; // esi
  DWORD v9; // ecx
  LPVOID v10; // esi
  struct _SYSTEM_INFO SystemInfo; // [esp+Ch] [ebp-24h] BYREF

  v4 = CreateFileA(lpFileName, 0xC0000000, 0, 0, 3u, 0, 0);
  v5 = v4;
  if ( v4 == (HANDLE)-1 )
    return 0;
  if ( a4 )
    *(_DWORD *)a4 = GetFileSize(v4, 0);
  v7 = CreateFileMappingA(v5, 0, 4u, 0, 0, 0);
  CloseHandle(v5);
  if ( !v7 )
    return 0;
  v8 = 0;
  if ( a2 )
  {
    v8 = *(_DWORD *)a2;
    GetSystemInfo(&SystemInfo);
    v9 = *(_DWORD *)a2;
    if ( *(_DWORD *)a2 % SystemInfo.dwAllocationGranularity )
    {
      v8 = SystemInfo.dwAllocationGranularity * (v9 / SystemInfo.dwAllocationGranularity);
      *(_DWORD *)a2 = v8;
      dwNumberOfBytesToMap += v9 - v8;
    }
  }
  v10 = MapViewOfFile(v7, 0xF001Fu, 0, v8, dwNumberOfBytesToMap);
  CloseHandle(v7);
  return v10;
}

//----- (00000240) --------------------------------------------------------
void __thiscall CFileMapping::OpenCreate(CFileMapping *this, LPCSTR lpFileName, LONG lDistanceToMove)
{
  HANDLE v4; // eax

  CFileMapping::Close(this);
  v4 = OpenFileMappingCreate(lpFileName, (int)this, lDistanceToMove);
  *((_DWORD *)this + 1) = v4;
  if ( v4 )
    *((_DWORD *)this + 2) = lDistanceToMove;
}

//----- (00000270) --------------------------------------------------------
HANDLE __cdecl OpenFileMappingCreate(LPCSTR lpFileName, int a2, LONG lDistanceToMove)
{
  HANDLE result; // eax
  HANDLE v4; // esi
  LPVOID v5; // edi

  if ( *(_DWORD *)a2 == -1 )
    *(_DWORD *)a2 = CreateFileA(lpFileName, 0xC0000000, 0, 0, 4u, 0, 0);
  if ( *(_DWORD *)a2 == -1 )
    return 0;
  SetFilePointer(*(HANDLE *)a2, lDistanceToMove, 0, 0);
  SetEndOfFile(*(HANDLE *)a2);
  result = CreateFileMappingA(*(HANDLE *)a2, 0, 4u, 0, 0, 0);
  v4 = result;
  if ( result )
  {
    v5 = MapViewOfFile(result, 0xF001Fu, 0, 0, 0);
    CloseHandle(v4);
    result = v5;
  }
  return result;
}

//----- (00000300) --------------------------------------------------------
void __thiscall CFileMapping::ReOpenCreate(CFileMapping *this, LONG lDistanceToMove)
{
  HANDLE v3; // eax

  if ( *((_DWORD *)this + 1) )
    UnmapViewOfFile(*((LPCVOID *)this + 1));
  v3 = OpenFileMappingCreate(0, (int)this, lDistanceToMove);
  *((_DWORD *)this + 1) = v3;
  if ( v3 )
    *((_DWORD *)this + 2) = lDistanceToMove;
}

//----- (00000340) --------------------------------------------------------
void __thiscall CFileMapping::Close(CFileMapping *this)
{
  if ( *((_DWORD *)this + 1) )
  {
    UnmapViewOfFile(*((LPCVOID *)this + 1));
    *((_DWORD *)this + 1) = 0;
  }
  if ( *(_DWORD *)this != -1 )
  {
    CloseHandle(*(HANDLE *)this);
    *(_DWORD *)this = -1;
  }
}

// nfuncs=19 queued=9 decompiled=9 lumina nreq=0 worse=0 better=0
// ALL OK, 9 function(s) have been successfully decompiled
