/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

_DWORD *__cdecl MD5Init(_DWORD *a1);
void __cdecl MD5Transform(int *a1, int a2);
void __cdecl Encode(int a1, _BYTE *a2, unsigned int a3);
void __cdecl Decode(int a1, int a2, unsigned int a3);
void __cdecl MD5_memcpy(_BYTE *a1, int a2, int a3);
// void __usercall MD5_memset(int a1@<ebx>, char *a2, char a3, unsigned int a4);


//----- (00000040) --------------------------------------------------------
_DWORD *__cdecl MD5Init(_DWORD *a1)
{
  _DWORD *result; // eax

  result = a1;
  a1[5] = 0;
  a1[4] = 0;
  *a1 = 1732584193;
  a1[1] = -271733879;
  a1[2] = -1732584194;
  a1[3] = 271733878;
  return result;
}
// 83: control flows out of bounds to 35

//----- (00000210) --------------------------------------------------------
void __cdecl MD5Transform(int *a1, int a2)
{
  int v3; // edi
  int v4; // ebx
  int v5; // ebp
  unsigned __int64 v6; // kr00_8
  int v7; // eax
  unsigned __int64 v8; // kr08_8
  int v9; // ecx
  unsigned int v10; // ebx
  int v11; // edx
  int v12; // edi
  int v13; // edi
  unsigned int v14; // ecx
  int v15; // eax
  unsigned int v16; // edx
  int v17; // ecx
  unsigned int v18; // edi
  int v19; // edx
  unsigned int v20; // eax
  int v21; // edi
  unsigned int v22; // ecx
  int v23; // eax
  unsigned int v24; // edx
  int v25; // ecx
  unsigned int v26; // edi
  int v27; // edx
  unsigned int v28; // eax
  int v29; // edi
  unsigned int v30; // ecx
  int v31; // eax
  unsigned int v32; // edx
  int v33; // ecx
  unsigned int v34; // edi
  int v35; // edx
  unsigned int v36; // eax
  int v37; // edi
  unsigned int v38; // ecx
  int v39; // eax
  unsigned int v40; // edx
  int v41; // ecx
  unsigned int v42; // edi
  int v43; // edx
  unsigned int v44; // eax
  int v45; // edi
  unsigned int v46; // ecx
  int v47; // eax
  unsigned int v48; // edx
  int v49; // ecx
  unsigned int v50; // edi
  int v51; // edx
  unsigned int v52; // eax
  unsigned int v53; // edi
  unsigned int v54; // eax
  unsigned int v55; // ecx
  unsigned int v56; // ebx
  unsigned int v57; // edx
  unsigned int v58; // edi
  unsigned int v59; // eax
  unsigned int v60; // ecx
  unsigned int v61; // ebx
  unsigned int v62; // eax
  unsigned int v63; // edx
  unsigned int v64; // ebx
  unsigned int v65; // edi
  unsigned int v66; // edx
  unsigned int v67; // ecx
  unsigned int v68; // eax
  unsigned int v69; // ebx
  unsigned int v70; // edi
  unsigned int v71; // edx
  unsigned int v72; // ebx
  unsigned int v73; // ecx
  unsigned int v74; // eax
  unsigned int v75; // edi
  unsigned int v76; // edx
  unsigned int v77; // ebx
  unsigned int v78; // edi
  unsigned int v79; // ecx
  unsigned int v80; // ebx
  unsigned int v81; // eax
  unsigned int v82; // ecx
  unsigned int v83; // edx
  int v84; // eax
  unsigned int v85; // edi
  int v86; // edx
  unsigned int v87; // ebx
  int v88; // edi
  unsigned int v89; // ecx
  int v90; // ebx
  unsigned int v91; // eax
  int v92; // ecx
  unsigned int v93; // edx
  int v94; // eax
  unsigned int v95; // edi
  int v96; // edx
  unsigned int v97; // ebx
  int v98; // edi
  unsigned int v99; // ecx
  int v100; // ebx
  unsigned int v101; // eax
  int v102; // ecx
  unsigned int v103; // edx
  int v104; // eax
  unsigned int v105; // edi
  int v106; // edx
  unsigned int v107; // ebx
  int v108; // edi
  unsigned int v109; // ecx
  int v110; // ebx
  int v111; // ebp
  unsigned int v112; // eax
  int v113; // ecx
  int v114; // edx
  int v115; // ebx
  int v116; // [esp+10h] [ebp-40h] BYREF
  int v117; // [esp+14h] [ebp-3Ch]
  int v118; // [esp+18h] [ebp-38h]
  int v119; // [esp+1Ch] [ebp-34h]
  int v120; // [esp+20h] [ebp-30h]
  int v121; // [esp+24h] [ebp-2Ch]
  int v122; // [esp+28h] [ebp-28h]
  int v123; // [esp+2Ch] [ebp-24h]
  int v124; // [esp+30h] [ebp-20h]
  int v125; // [esp+34h] [ebp-1Ch]
  int v126; // [esp+38h] [ebp-18h]
  int v127; // [esp+3Ch] [ebp-14h]
  int v128; // [esp+40h] [ebp-10h]
  int v129; // [esp+44h] [ebp-Ch]
  int v130; // [esp+48h] [ebp-8h]
  int v131; // [esp+4Ch] [ebp-4h]
  int v132; // [esp+54h] [ebp+4h]
  int v133; // [esp+54h] [ebp+4h]
  int v134; // [esp+54h] [ebp+4h]
  int v135; // [esp+54h] [ebp+4h]
  int v136; // [esp+54h] [ebp+4h]
  int v137; // [esp+54h] [ebp+4h]
  int v138; // [esp+54h] [ebp+4h]
  int v139; // [esp+54h] [ebp+4h]

  v3 = a1[1];
  v4 = a1[2];
  v5 = a1[3];
  v132 = *a1;
  Decode((int)&v116, a2, 0x40u);
  v6 = (unsigned __int64)(v132 + v116 + (v3 & v4 | v5 & (unsigned int)~v3) - 680876936) << 7;
  v7 = v3 + (v6 | HIDWORD(v6));
  v8 = (unsigned __int64)(v117 + (v7 & v3 | v4 & (unsigned int)~v7) + v5 - 389564586) << 12;
  v9 = v7 + (v8 | HIDWORD(v8));
  v10 = v4 + v118 + (v7 & v9 | v3 & ~v9) + 606105819;
  v11 = v9 + ((v10 << 17) | (v10 >> 15));
  v133 = v11
       + (((v3 + v119 + (v11 & v9 | v7 & (unsigned int)~v11) - 1044525330) >> 10) | ((v3
                                                                                    + v119
                                                                                    + (v11 & v9 | v7 & ~v11)
                                                                                    - 1044525330) << 22));
  v12 = v120 + (v133 & v11 | v9 & ~v133);
  v13 = v133 + (((v7 + v12 - 176418897) << 7) | ((unsigned int)(v7 + v12 - 176418897) >> 25));
  v14 = v9 + v121 + (v13 & v133 | v11 & ~v13) + 1200080426;
  v15 = v13 + ((v14 << 12) | (v14 >> 20));
  v16 = v11 + v122 + (v13 & v15 | v133 & ~v15) - 1473231341;
  v17 = v15 + ((v16 << 17) | (v16 >> 15));
  v134 = v17
       + (((v133 + v123 + (v17 & v15 | v13 & (unsigned int)~v17) - 45705983) >> 10) | ((v133
                                                                                      + v123
                                                                                      + (v17 & v15 | v13 & ~v17)
                                                                                      - 45705983) << 22));
  v18 = v13 + v124 + (v134 & v17 | v15 & ~v134) + 1770035416;
  v19 = v134 + ((v18 << 7) | (v18 >> 25));
  v20 = v15 + v125 + (v19 & v134 | v17 & ~v19) - 1958414417;
  v21 = v19 + ((v20 << 12) | (v20 >> 20));
  v22 = v17 + v126 + (v19 & v21 | v134 & ~v21) - 42063;
  v23 = v21 + ((v22 << 17) | (v22 >> 15));
  v135 = v23
       + (((v134 + v127 + (v23 & v21 | v19 & (unsigned int)~v23) - 1990404162) >> 10) | ((v134
                                                                                        + v127
                                                                                        + (v23 & v21 | v19 & ~v23)
                                                                                        - 1990404162) << 22));
  v24 = v19 + v128 + (v135 & v23 | v21 & ~v135) + 1804603682;
  v25 = v135 + ((v24 << 7) | (v24 >> 25));
  v26 = v21 + v129 + (v25 & v135 | v23 & ~v25) - 40341101;
  v27 = v25 + ((v26 << 12) | (v26 >> 20));
  v28 = v23 + v130 + (~v27 & v135 | v25 & v27) - 1502002290;
  v29 = v27 + ((v28 << 17) | (v28 >> 15));
  v136 = v29
       + (((v135 + v131 + (v29 & v27 | v25 & (unsigned int)~v29) + 1236535329) >> 10) | ((v135
                                                                                        + v131
                                                                                        + (v29 & v27 | v25 & ~v29)
                                                                                        + 1236535329) << 22));
  v30 = v25 + v117 + (~v27 & v29 | v136 & v27) - 165796510;
  v31 = v136 + ((32 * v30) | (v30 >> 27));
  v32 = v27 + v122 + (v31 & v29 | v136 & ~v29) - 1069501632;
  v33 = v31 + ((v32 << 9) | (v32 >> 23));
  v34 = v29 + v127 + (v136 & v33 | v31 & ~v136) + 643717713;
  v35 = v33 + ((v34 << 14) | (v34 >> 18));
  v137 = v35
       + (((v136 + v116 + (v31 & v35 | v33 & (unsigned int)~v31) - 373897302) >> 12) | ((v136
                                                                                       + v116
                                                                                       + (v31 & v35 | v33 & ~v31)
                                                                                       - 373897302) << 20));
  v36 = v31 + v121 + (v137 & v33 | v35 & ~v33) - 701558691;
  v37 = v137 + ((32 * v36) | (v36 >> 27));
  v38 = v33 + v126 + (v37 & v35 | v137 & ~v35) + 38016083;
  v39 = v37 + ((v38 << 9) | (v38 >> 23));
  v40 = v35 + v131 + (v137 & v39 | v37 & ~v137) - 660478335;
  v41 = v39 + ((v40 << 14) | (v40 >> 18));
  v138 = v41
       + (((v137 + v120 + (v37 & v41 | v39 & (unsigned int)~v37) - 405537848) >> 12) | ((v137
                                                                                       + v120
                                                                                       + (v37 & v41 | v39 & ~v37)
                                                                                       - 405537848) << 20));
  v42 = v37 + v125 + (v138 & v39 | v41 & ~v39) + 568446438;
  v43 = v138 + ((32 * v42) | (v42 >> 27));
  v44 = v39 + v130 + (v43 & v41 | v138 & ~v41) - 1019803690;
  v45 = v43 + ((v44 << 9) | (v44 >> 23));
  v46 = v41 + v119 + (v138 & v45 | v43 & ~v138) - 187363961;
  v47 = v45 + ((v46 << 14) | (v46 >> 18));
  v139 = v47
       + (((v138 + v124 + (v43 & v47 | v45 & (unsigned int)~v43) + 1163531501) >> 12) | ((v138
                                                                                        + v124
                                                                                        + (v43 & v47 | v45 & ~v43)
                                                                                        + 1163531501) << 20));
  v48 = v43 + v129 + (v139 & v45 | v47 & ~v45) - 1444681467;
  v49 = v139 + ((32 * v48) | (v48 >> 27));
  v50 = v45 + v118 + (v49 & v47 | v139 & ~v47) - 51403784;
  v51 = v49 + ((v50 << 9) | (v50 >> 23));
  v52 = v47 + v123 + (v139 & v51 | v49 & ~v139) + 1735328473;
  v53 = v51 + ((v52 << 14) | (v52 >> 18));
  v54 = v53
      + (((v139 + v128 + (v49 & v53 | v51 & ~v49) - 1926607734) >> 12) | ((v139
                                                                         + v128
                                                                         + (v49 & v53 | v51 & ~v49)
                                                                         - 1926607734) << 20));
  v55 = v49 + v121 + (v54 ^ v53 ^ v51) - 378558;
  v56 = v54 + ((16 * v55) | (v55 >> 28));
  v57 = v56
      + (((v51 + v124 + (v56 ^ v54 ^ v53) - 2022574463) << 11) | ((v51 + v124 + (v56 ^ v54 ^ v53) - 2022574463) >> 21));
  v58 = v57
      + (((v53 + v127 + (v56 ^ v54 ^ v57) + 1839030562) << 16) | ((v53 + v127 + (v56 ^ v54 ^ v57) + 1839030562) >> 16));
  v59 = v54 + v130 + (v56 ^ v58 ^ v57) - 35309556;
  v60 = v58 + ((v59 >> 9) | (v59 << 23));
  v61 = v56 + v117 + (v60 ^ v58 ^ v57) - 1530992060;
  v62 = v60 + ((16 * v61) | (v61 >> 28));
  v63 = v57 + v120 + (v62 ^ v60 ^ v58) + 1272893353;
  v64 = v62 + ((v63 << 11) | (v63 >> 21));
  v65 = v58 + v123 + (v62 ^ v60 ^ v64) - 155497632;
  v66 = v64 + ((v65 << 16) | HIWORD(v65));
  v67 = v66
      + (((v60 + v126 + (v62 ^ v66 ^ v64) - 1094730640) >> 9) | ((v60 + v126 + (v62 ^ v66 ^ v64) - 1094730640) << 23));
  v68 = v67
      + ((16 * (v62 + v129 + (v67 ^ v66 ^ v64) + 681279174)) | ((v62 + v129 + (v67 ^ v66 ^ v64) + 681279174) >> 28));
  v69 = v64 + v116 + (v68 ^ v67 ^ v66) - 358537222;
  v70 = v68 + ((v69 << 11) | (v69 >> 21));
  v71 = v66 + v119 + (v68 ^ v67 ^ v70) - 722521979;
  v72 = v70 + ((v71 << 16) | HIWORD(v71));
  v73 = v72 + (((v67 + v122 + (v68 ^ v72 ^ v70) + 76029189) >> 9) | ((v67 + v122 + (v68 ^ v72 ^ v70) + 76029189) << 23));
  v74 = v73
      + ((16 * (v68 + v125 + (v73 ^ v72 ^ v70) - 640364487)) | ((v68 + v125 + (v73 ^ v72 ^ v70) - 640364487) >> 28));
  v75 = v70 + v128 + (v74 ^ v73 ^ v72) - 421815835;
  v76 = v74 + ((v75 << 11) | (v75 >> 21));
  v77 = v72 + v131 + (v74 ^ v73 ^ v76) + 530742520;
  v78 = v76 + ((v77 << 16) | HIWORD(v77));
  v79 = v73 + v118 + (v74 ^ v78 ^ v76) - 995338651;
  v80 = v78 + ((v79 >> 9) | (v79 << 23));
  v81 = v74 + v116 + (v78 ^ (v80 | ~v76)) - 198630844;
  v82 = v80 + ((v81 << 6) | (v81 >> 26));
  v83 = v76 + v123 + (v80 ^ (v82 | ~v78)) + 1126891415;
  v84 = v82 + ((v83 << 10) | (v83 >> 22));
  v85 = v78 + v130 + (v82 ^ (v84 | ~v80)) - 1416354905;
  v86 = v84 + ((v85 << 15) | (v85 >> 17));
  v87 = v80 + v121 + (v84 ^ (v86 | ~v82)) - 57434055;
  v88 = v86 + ((v87 >> 11) | (v87 << 21));
  v89 = v82 + v128 + (v86 ^ (v88 | ~v84)) + 1700485571;
  v90 = v88 + ((v89 << 6) | (v89 >> 26));
  v91 = v84 + v119 + (v88 ^ (v90 | ~v86)) - 1894986606;
  v92 = v90 + ((v91 << 10) | (v91 >> 22));
  v93 = v86 + v126 + (v90 ^ (v92 | ~v88)) - 1051523;
  v94 = v92 + ((v93 << 15) | (v93 >> 17));
  v95 = v88 + v117 + (v92 ^ (v94 | ~v90)) - 2054922799;
  v96 = v94 + ((v95 >> 11) | (v95 << 21));
  v97 = v90 + v124 + (v94 ^ (v96 | ~v92)) + 1873313359;
  v98 = v96 + ((v97 << 6) | (v97 >> 26));
  v99 = v92 + v131 + (v96 ^ (v98 | ~v94)) - 30611744;
  v100 = v98 + ((v99 << 10) | (v99 >> 22));
  v101 = v94 + v122 + (v98 ^ (v100 | ~v96)) - 1560198380;
  v102 = v100 + ((v101 << 15) | (v101 >> 17));
  v103 = v96 + v129 + (v100 ^ (v102 | ~v98)) + 1309151649;
  v104 = v102 + ((v103 >> 11) | (v103 << 21));
  v105 = v98 + v120 + (v102 ^ (v104 | ~v100)) - 145523070;
  v106 = v104 + ((v105 << 6) | (v105 >> 26));
  v107 = v100 + v127 + (v104 ^ (v106 | ~v102)) - 1120210379;
  v108 = v106 + ((v107 << 10) | (v107 >> 22));
  v109 = v102 + v118 + (v106 ^ (v108 | ~v104)) + 718787259;
  v110 = v108 + ((v109 << 15) | (v109 >> 17));
  v111 = v110 + a1[2];
  v112 = v104 + v125 + (v108 ^ (v110 | ~v106)) - 343485551;
  v113 = v106 + *a1;
  v114 = v110 + ((v112 >> 11) | (v112 << 21));
  v115 = v108 + a1[3];
  a1[1] += v114;
  *a1 = v113;
  a1[2] = v111;
  a1[3] = v115;
  MD5_memset(v115, (char *)&v116, 0, 0x40u);
}
// 210: too many cbuild loops

//----- (00000B60) --------------------------------------------------------
void __cdecl Encode(int a1, _BYTE *a2, unsigned int a3)
{
  _BYTE *v4; // eax
  char v5; // dl

  if ( a3 )
  {
    v4 = (_BYTE *)(a1 + 1);
    do
    {
      v5 = *a2;
      a2 += 4;
      *(v4 - 1) = v5;
      *v4 = BYTE1(*((_DWORD *)a2 - 1));
      v4[1] = BYTE2(*((_DWORD *)a2 - 1));
      v4[2] = HIBYTE(*((_DWORD *)a2 - 1));
      v4 += 4;
    }
    while ( (unsigned int)&v4[-1 - a1] < a3 );
  }
}

//----- (00000BB0) --------------------------------------------------------
void __cdecl Decode(int a1, int a2, unsigned int a3)
{
  unsigned __int16 *v4; // eax
  unsigned __int16 v5; // cx
  int v6; // edx

  if ( a3 )
  {
    v4 = (unsigned __int16 *)(a2 + 2);
    do
    {
      v5 = *v4;
      v6 = *((unsigned __int8 *)v4 - 1);
      v4 += 2;
      a1 += 4;
      *(_DWORD *)(a1 - 4) = *((unsigned __int8 *)v4 - 6) | ((v6 | (v5 << 8)) << 8);
    }
    while ( (unsigned int)v4 - 2 - a2 < a3 );
  }
}

//----- (00000C00) --------------------------------------------------------
void __cdecl MD5_memcpy(_BYTE *a1, int a2, int a3)
{
  int v3; // esi
  _BYTE *v4; // eax

  v3 = a3;
  if ( a3 )
  {
    v4 = a1;
    do
    {
      *v4 = v4[a2 - (_DWORD)a1];
      ++v4;
      --v3;
    }
    while ( v3 );
  }
}

//----- (00000C20) --------------------------------------------------------
void __usercall MD5_memset(int a1@<ebx>, char *a2, char a3, unsigned int a4)
{
  int v4; // eax

  if ( a4 )
  {
    LOBYTE(a1) = a3;
    BYTE1(a1) = a3;
    v4 = a1 << 16;
    LOWORD(v4) = a1;
    memset32(a2, v4, a4 >> 2);
    memset(&a2[4 * (a4 >> 2)], a3, a4 & 3);
  }
}
// C20: could not find valid save-restore pair for ebx

// nfuncs=6 queued=6 decompiled=6 lumina nreq=0 worse=0 better=0
// ALL OK, 6 function(s) have been successfully decompiled
