/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <math.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

double __thiscall CMersenneTwister::rand(CMersenneTwister *__hidden this); // idb
double __thiscall CMersenneTwister::rand(CMersenneTwister *__hidden this, const double *); // idb
double __thiscall CMersenneTwister::randEx(CMersenneTwister *__hidden this); // idb
double __thiscall CMersenneTwister::randEx(CMersenneTwister *__hidden this, const double *); // idb
double __thiscall CMersenneTwister::randDblEx(CMersenneTwister *__hidden this); // idb
double __thiscall CMersenneTwister::randDblEx(CMersenneTwister *__hidden this, const double *); // idb
double __thiscall CMersenneTwister::rand53(CMersenneTwister *__hidden this); // idb
long double __thiscall CMersenneTwister::randNorm(CMersenneTwister *this, const double *a2, const double *a3);
int __thiscall CMersenneTwister::randInt(CMersenneTwister *this);
unsigned int __thiscall CMersenneTwister::randInt(CMersenneTwister *__hidden this, const unsigned int *); // idb
void __thiscall CMersenneTwister::seed(CMersenneTwister *__hidden this, const unsigned int *); // idb
void __thiscall CMersenneTwister::seed(CMersenneTwister *__hidden this, unsigned int *const, unsigned int); // idb
void __thiscall CMersenneTwister::seed(CMersenneTwister *__hidden this); // idb
void __thiscall CMersenneTwister::Initialize(CMersenneTwister *__hidden this, unsigned int); // idb
void __thiscall CMersenneTwister::ReloadState(CMersenneTwister *__hidden this); // idb
unsigned int __thiscall CMersenneTwister::HiBit(CMersenneTwister *__hidden this, const unsigned int *); // idb
unsigned int __thiscall CMersenneTwister::LoBit(CMersenneTwister *__hidden this, const unsigned int *); // idb
unsigned int __thiscall CMersenneTwister::LoBits(CMersenneTwister *__hidden this, const unsigned int *); // idb
unsigned int __thiscall CMersenneTwister::MixBits(CMersenneTwister *__hidden this, const unsigned int *, const unsigned int *); // idb
unsigned int __thiscall CMersenneTwister::Twist(CMersenneTwister *__hidden this, const unsigned int *, const unsigned int *, const unsigned int *); // idb
int __thiscall CMersenneTwister::Hash(CMersenneTwister *this, char a2, int a3);
CMersenneTwister *__thiscall CMersenneTwister::CMersenneTwister(CMersenneTwister *__hidden this, const unsigned int *); // idb
CMersenneTwister *__thiscall CMersenneTwister::CMersenneTwister(CMersenneTwister *__hidden this, unsigned int *const, unsigned int); // idb
CMersenneTwister *__thiscall CMersenneTwister::CMersenneTwister(CMersenneTwister *__hidden this); // idb
// __time32_t __cdecl time(__time32_t *const Time);
// clock_t __cdecl clock();

//-------------------------------------------------------------------------
// Data declarations

int _dwDiffer__1__Hash_CMersenneTwister__IAEKJJ_Z_4KA; // weak


//----- (00000004) --------------------------------------------------------
double __thiscall CMersenneTwister::rand(CMersenneTwister *this)
{
  return (double)(unsigned int)CMersenneTwister::randInt(this) * 2.328306437080797e-10;
}

//----- (0000003C) --------------------------------------------------------
double __thiscall CMersenneTwister::rand(CMersenneTwister *this, const double *a2)
{
  return CMersenneTwister::rand(this) * *a2;
}

//----- (0000004C) --------------------------------------------------------
double __thiscall CMersenneTwister::randEx(CMersenneTwister *this)
{
  return (double)(unsigned int)CMersenneTwister::randInt(this) * 2.328306436538696e-10;
}

//----- (00000084) --------------------------------------------------------
double __thiscall CMersenneTwister::randEx(CMersenneTwister *this, const double *a2)
{
  return CMersenneTwister::randEx(this) * *a2;
}

//----- (00000094) --------------------------------------------------------
double __thiscall CMersenneTwister::randDblEx(CMersenneTwister *this)
{
  return ((double)(unsigned int)CMersenneTwister::randInt(this) + 0.5) * 2.328306436538696e-10;
}

//----- (000000CC) --------------------------------------------------------
double __thiscall CMersenneTwister::randDblEx(CMersenneTwister *this, const double *a2)
{
  return CMersenneTwister::randDblEx(this) * *a2;
}

//----- (000000DC) --------------------------------------------------------
double __thiscall CMersenneTwister::rand53(CMersenneTwister *this)
{
  unsigned int v2; // esi
  __int64 v4; // [esp+8h] [ebp-8h]

  v2 = (unsigned int)CMersenneTwister::randInt(this) >> 5;
  v4 = v2;
  LODWORD(v4) = (unsigned int)CMersenneTwister::randInt(this) >> 6;
  return ((double)v2 * 67108864.0 + (double)v4) * 1.110223024625157e-16;
}

//----- (0000013C) --------------------------------------------------------
long double __thiscall CMersenneTwister::randNorm(CMersenneTwister *this, const double *a2, const double *a3)
{
  long double v5; // [esp+4h] [ebp-8h]

  v5 = sqrt(__FYL2X__(1.0 - CMersenneTwister::randDblEx(this), 0.69314718055994528623) * -2.0) * *a3;
  return cos(CMersenneTwister::randEx(this) * 6.283185307179586) * v5 + *a2;
}

//----- (000001A4) --------------------------------------------------------
int __thiscall CMersenneTwister::randInt(CMersenneTwister *this)
{
  unsigned int *v2; // eax
  unsigned int v3; // ecx
  unsigned int v4; // ecx

  if ( !*((_DWORD *)this + 625) )
    CMersenneTwister::ReloadState(this);
  --*((_DWORD *)this + 625);
  v2 = (unsigned int *)*((_DWORD *)this + 624);
  v3 = *v2;
  *((_DWORD *)this + 624) = v2 + 1;
  v4 = (((((((v3 >> 11) ^ v3) & 0xFF3A58AD) << 7) ^ (v3 >> 11) ^ v3) & 0xFFFFDF8C) << 15) ^ ((((v3 >> 11) ^ v3) & 0xFF3A58AD) << 7) ^ (v3 >> 11) ^ v3;
  return v4 ^ (v4 >> 18);
}

//----- (00000204) --------------------------------------------------------
unsigned int __thiscall CMersenneTwister::randInt(CMersenneTwister *this, const unsigned int *a2)
{
  unsigned int v3; // eax
  unsigned int v4; // ecx
  unsigned int v5; // esi
  unsigned int result; // eax

  v3 = ((((*a2 >> 1) | *a2) >> 2) | (*a2 >> 1) | *a2) >> 4;
  v4 = (v3 | (((*a2 >> 1) | *a2) >> 2) | (*a2 >> 1) | *a2) >> 8;
  v5 = ((v4 | v3 | (((*a2 >> 1) | *a2) >> 2) | (*a2 >> 1) | *a2) >> 16) | v4 | v3 | (((*a2 >> 1) | *a2) >> 2) | (*a2 >> 1) | *a2;
  do
    result = v5 & CMersenneTwister::randInt(this);
  while ( result > v5 );
  return result;
}

//----- (00000244) --------------------------------------------------------
void __thiscall CMersenneTwister::seed(CMersenneTwister *this, const unsigned int *a2)
{
  CMersenneTwister::Initialize(this, *a2);
  CMersenneTwister::ReloadState(this);
}

//----- (00000264) --------------------------------------------------------
void __thiscall CMersenneTwister::seed(CMersenneTwister *this, unsigned int *const a2, unsigned int a3)
{
  unsigned int v5; // ecx
  int v6; // eax
  unsigned int v7; // edx
  int v8; // edx
  int v9; // edx
  unsigned int v10; // [esp+18h] [ebp+8h]

  CMersenneTwister::Initialize(this, 0x12BD6AAu);
  v5 = 0;
  v6 = 1;
  if ( a3 >= 0x270 )
    v7 = a3;
  else
    v7 = 624;
  v10 = v7;
  do
  {
    v8 = (1664525 * (*((_DWORD *)this + v6 - 1) ^ (*((_DWORD *)this + v6 - 1) >> 30))) ^ *((_DWORD *)this + v6);
    *((_DWORD *)this + v6) = v8;
    *((_DWORD *)this + v6++) = v5 + v8 + a2[v5];
    ++v5;
    if ( v6 >= 624 )
    {
      *(_DWORD *)this = *((_DWORD *)this + 623);
      v6 = 1;
    }
    if ( v5 >= a3 )
      v5 = 0;
    --v10;
  }
  while ( v10 );
  v9 = 623;
  do
  {
    *((_DWORD *)this + v6) = (*((_DWORD *)this + v6) ^ (1566083941
                                                      * (*((_DWORD *)this + v6 - 1) ^ (*((_DWORD *)this + v6 - 1) >> 30))))
                           - v6;
    if ( ++v6 >= 624 )
    {
      v6 = 1;
      *(_DWORD *)this = *((_DWORD *)this + 623);
    }
    --v9;
  }
  while ( v9 );
  *(_DWORD *)this = 0x80000000;
  CMersenneTwister::ReloadState(this);
}
// 292: conditional instruction was optimized away because of '%arg_4.4>=270u'

//----- (00000334) --------------------------------------------------------
void __thiscall CMersenneTwister::seed(CMersenneTwister *this)
{
  char v2; // al
  int v3; // [esp-4h] [ebp-Ch]
  unsigned int v4; // [esp+4h] [ebp-4h] BYREF

  v3 = clock();
  v2 = time(0);
  v4 = CMersenneTwister::Hash(this, v2, v3);
  CMersenneTwister::seed(this, &v4);
}

//----- (00000364) --------------------------------------------------------
void __thiscall CMersenneTwister::Initialize(CMersenneTwister *this, unsigned int a2)
{
  int v2; // eax
  unsigned int v3; // edx
  int v4; // esi

  v2 = 1;
  *(_DWORD *)this = a2;
  do
  {
    v3 = *(_DWORD *)this;
    this = (CMersenneTwister *)((char *)this + 4);
    v4 = v2 + 1812433253 * (v3 ^ (v3 >> 30));
    ++v2;
    *(_DWORD *)this = v4;
  }
  while ( v2 < 624 );
}

//----- (00000394) --------------------------------------------------------
void __thiscall CMersenneTwister::ReloadState(CMersenneTwister *this)
{
  CMersenneTwister *v1; // edi
  int v2; // ebx
  unsigned int *v3; // esi
  const unsigned int *v4; // ebx
  int v5; // ebp

  v1 = this;
  v2 = 227;
  v3 = (unsigned int *)this;
  do
  {
    *v3 = CMersenneTwister::Twist(v1, v3 + 397, v3, v3 + 1);
    ++v3;
    --v2;
  }
  while ( v2 );
  v4 = v3 - 227;
  v5 = 396;
  do
  {
    *v3 = CMersenneTwister::Twist(v1, v4, v3, v4 + 228);
    ++v3;
    ++v4;
    --v5;
  }
  while ( v5 );
  *v3 = CMersenneTwister::Twist(v1, v3 - 227, v3, (const unsigned int *)v1);
  *((_DWORD *)v1 + 625) = 624;
  *((_DWORD *)v1 + 624) = v1;
}

//----- (00000414) --------------------------------------------------------
unsigned int __thiscall CMersenneTwister::HiBit(CMersenneTwister *this, const unsigned int *a2)
{
  return *a2 & 0x80000000;
}

//----- (00000424) --------------------------------------------------------
unsigned int __thiscall CMersenneTwister::LoBit(CMersenneTwister *this, const unsigned int *a2)
{
  return *a2 & 1;
}

//----- (00000434) --------------------------------------------------------
unsigned int __thiscall CMersenneTwister::LoBits(CMersenneTwister *this, const unsigned int *a2)
{
  return *a2 & 0x7FFFFFFF;
}

//----- (00000444) --------------------------------------------------------
unsigned int __thiscall CMersenneTwister::MixBits(CMersenneTwister *this, const unsigned int *a2, const unsigned int *a3)
{
  unsigned int v4; // edi

  v4 = CMersenneTwister::HiBit(this, a2);
  return v4 | CMersenneTwister::LoBits(this, a3);
}

//----- (00000474) --------------------------------------------------------
unsigned int __thiscall CMersenneTwister::Twist(CMersenneTwister *this, const unsigned int *a2, const unsigned int *a3, const unsigned int *a4)
{
  unsigned int v5; // ebx

  v5 = CMersenneTwister::MixBits(this, a3, a4) >> 1;
  return -CMersenneTwister::LoBit(this, a3) & 0x9908B0DF ^ v5 ^ *a2;
}

//----- (000004B4) --------------------------------------------------------
int __thiscall CMersenneTwister::Hash(CMersenneTwister *this, char a2, int a3)
{
  int v3; // esi
  unsigned int i; // eax
  int v5; // edx
  int v6; // ecx
  unsigned int j; // eax
  int v8; // edx
  int result; // eax

  v3 = 0;
  for ( i = 0; i < 4; ++i )
  {
    v5 = 257 * v3 + (unsigned __int8)*(&a2 + i);
    v3 = v5;
  }
  v6 = 0;
  for ( j = 0; j < 4; ++j )
  {
    v8 = 257 * v6 + *((unsigned __int8 *)&a3 + j);
    v6 = v8;
  }
  result = v8 ^ (_dwDiffer__1__Hash_CMersenneTwister__IAEKJJ_Z_4KA + v3);
  ++_dwDiffer__1__Hash_CMersenneTwister__IAEKJJ_Z_4KA;
  return result;
}
// 0: using guessed type int _dwDiffer__1__Hash_CMersenneTwister__IAEKJJ_Z_4KA;

//----- (00000514) --------------------------------------------------------
CMersenneTwister *__thiscall CMersenneTwister::CMersenneTwister(CMersenneTwister *this, const unsigned int *a2)
{
  CMersenneTwister::seed(this, a2);
  return this;
}

//----- (00000534) --------------------------------------------------------
CMersenneTwister *__thiscall CMersenneTwister::CMersenneTwister(CMersenneTwister *this, unsigned int *const a2, unsigned int a3)
{
  CMersenneTwister::seed(this, a2, a3);
  return this;
}

//----- (00000554) --------------------------------------------------------
CMersenneTwister *__thiscall CMersenneTwister::CMersenneTwister(CMersenneTwister *this)
{
  CMersenneTwister::seed(this);
  return this;
}

// nfuncs=26 queued=24 decompiled=24 lumina nreq=0 worse=0 better=0
// ALL OK, 24 function(s) have been successfully decompiled
