/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

CMersenneTwister *_E3();
void __thiscall CPolynomialTable::Randomize(CPolynomialTable *__hidden this); // idb
unsigned int *__thiscall CPolynomialTable::RandomStatic(CPolynomialTable *this);
unsigned int __thiscall CPolynomialTable::RandomDynamic(CPolynomialTable *__hidden this); // idb
unsigned int __thiscall CPolynomialTable::Reflect(CPolynomialTable *__hidden this, unsigned int, unsigned __int8); // idb
int __thiscall CPolynomialTable::operator[](_DWORD *this, int a2);
void __thiscall CPolynomialTable::GenerateTable(CPolynomialTable *__hidden this); // idb
CPolynomialTable *__thiscall CPolynomialTable::CPolynomialTable(CPolynomialTable *__hidden this); // idb
void __thiscall CPolynomialTable::~CPolynomialTable(CPolynomialTable *__hidden this); // idb
// CMersenneTwister *__thiscall CMersenneTwister::CMersenneTwister(CMersenneTwister *__hidden this); idb
// void __thiscall CMersenneTwister::seed(CMersenneTwister *__hidden this); idb
// unsigned int __thiscall CMersenneTwister::randInt(CMersenneTwister *__hidden this); idb
// void *__cdecl operator new(unsigned int); idb
// void __cdecl operator delete(void *); idb

//-------------------------------------------------------------------------
// Data declarations

unsigned int *CPolynomialTable::dwPolynomialTable = (unsigned int *)0x5EDEF90E; // weak
_UNKNOWN CPolynomialTable::rand; // weak


//----- (00000DDC) --------------------------------------------------------
CMersenneTwister *_E3()
{
  return CMersenneTwister::CMersenneTwister((CMersenneTwister *)&CPolynomialTable::rand);
}

//----- (00000DEC) --------------------------------------------------------
void __thiscall CPolynomialTable::Randomize(CPolynomialTable *this)
{
  CMersenneTwister::seed((CMersenneTwister *)&CPolynomialTable::rand);
}

//----- (00000DFC) --------------------------------------------------------
unsigned int *__thiscall CPolynomialTable::RandomStatic(CPolynomialTable *this)
{
  int v1; // eax

  CPolynomialTable::Randomize(this);
  v1 = (unsigned __int8)CMersenneTwister::randInt((CMersenneTwister *)&CPolynomialTable::rand);
  if ( v1 <= 0 )
    v1 %= 256;
  return (&CPolynomialTable::dwPolynomialTable)[v1];
}
// E17: conditional instruction was optimized away because of 'eax.4 in (1..FF)'
// 0: using guessed type unsigned int *CPolynomialTable::dwPolynomialTable;

//----- (00000E3C) --------------------------------------------------------
unsigned int __thiscall CPolynomialTable::RandomDynamic(CPolynomialTable *this)
{
  int v2; // eax
  unsigned int result; // eax

  if ( !*(_DWORD *)this )
    return 0;
  CPolynomialTable::Randomize(this);
  v2 = (unsigned __int8)CMersenneTwister::randInt((CMersenneTwister *)&CPolynomialTable::rand);
  if ( v2 <= 0 )
    result = *(_DWORD *)(*(_DWORD *)this + 4 * (v2 % 256));
  else
    result = *(_DWORD *)(*(_DWORD *)this + 4 * v2);
  return result;
}
// E5F: conditional instruction was optimized away because of 'eax.4 in (1..FF)'

//----- (00000E8C) --------------------------------------------------------
unsigned int __thiscall CPolynomialTable::Reflect(CPolynomialTable *this, unsigned int a2, unsigned __int8 a3)
{
  unsigned int result; // eax
  int v4; // esi
  char v6; // cl

  result = 0;
  if ( !__OFSUB__(a3 + 1, 1) && a3 != 0 )
  {
    v4 = a3;
    v6 = a3 - 1;
    do
    {
      if ( (a2 & 1) != 0 )
        result |= 1 << v6;
      a2 >>= 1;
      --v6;
      --v4;
    }
    while ( v4 );
  }
  return result;
}

//----- (00000ECC) --------------------------------------------------------
int __thiscall CPolynomialTable::operator[](_DWORD *this, int a2)
{
  int result; // eax

  if ( *this && a2 > 0 && a2 < 256 )
    result = *(_DWORD *)(*this + 4 * a2);
  else
    result = 0;
  return result;
}

//----- (00000EFC) --------------------------------------------------------
void __thiscall CPolynomialTable::GenerateTable(CPolynomialTable *this)
{
  signed int i; // edi
  int v3; // ebx
  unsigned int v4; // eax

  if ( *(_DWORD *)this )
  {
    operator delete(*(void **)this);
    *(_DWORD *)this = 0;
  }
  *(_DWORD *)this = operator new(0x400u);
  for ( i = 0; i < 256; *(_DWORD *)(*(_DWORD *)this + 4 * i - 4) = v4 )
  {
    v3 = 8;
    *(_DWORD *)(*(_DWORD *)this + 4 * i) = CPolynomialTable::Reflect(this, i, 8u) << 24;
    do
    {
      --v3;
      *(_DWORD *)(*(_DWORD *)this + 4 * i) = (2 * *(_DWORD *)(*(_DWORD *)this + 4 * i)) ^ (*(int *)(*(_DWORD *)this
                                                                                                  + 4 * i) < 0 ? (unsigned int)CPolynomialTable::RandomStatic(this) : 0);
    }
    while ( v3 );
    v4 = CPolynomialTable::Reflect(this, *(_DWORD *)(*(_DWORD *)this + 4 * i++), 0x20u);
  }
}

//----- (00000F8C) --------------------------------------------------------
CPolynomialTable *__thiscall CPolynomialTable::CPolynomialTable(CPolynomialTable *this)
{
  *(_DWORD *)this = 0;
  CPolynomialTable::GenerateTable(this);
  return this;
}

//----- (00000FAC) --------------------------------------------------------
void __thiscall CPolynomialTable::~CPolynomialTable(CPolynomialTable *this)
{
  if ( *(_DWORD *)this )
  {
    operator delete(*(void **)this);
    *(_DWORD *)this = 0;
  }
}

// nfuncs=15 queued=9 decompiled=9 lumina nreq=0 worse=0 better=0
// ALL OK, 9 function(s) have been successfully decompiled
