/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

void __cdecl __noreturn SeTranslator(unsigned int pExceptionObject);
Crwini *__thiscall Crwini::Crwini(Crwini *this);
Crwini *__thiscall Crwini::`scalar deleting destructor'(Crwini *this, char a2);
void __thiscall Crwini::~Crwini(Crwini *__hidden this); // idb
char __thiscall Crwini::WriteString(Crwini *this, LPCSTR lpAppName, LPCSTR lpKeyName, LPCSTR lpString, char *a5);
UINT __thiscall Crwini::GetInt(Crwini *this, LPCSTR lpAppName, LPCSTR lpKeyName, char *a4);
void __thiscall Crwini::ReadString(Crwini *__hidden this, LPCSTR lpAppName, LPCSTR lpKeyName, char *, char *const); // idb
void __thiscall Crwini::WriteInt(Crwini *__hidden this, LPCSTR lpKeyName, LPCSTR lpAppName, char *, int); // idb
void __cdecl DBSleep(DWORD dwMilliseconds); // idb
// void __stdcall __noreturn _CxxThrowException(void *pExceptionObject, _ThrowInfo *pThrowInfo);
// void __cdecl operator delete(void *); idb
// BOOL __stdcall WritePrivateProfileStringA(LPCSTR lpAppName, LPCSTR lpKeyName, LPCSTR lpString, LPCSTR lpFileName);
// char *__cdecl strrchr(const char *Str, int Ch);
// DWORD __stdcall GetModuleFileNameA(HMODULE hModule, LPSTR lpFilename, DWORD nSize);
// UINT __stdcall GetPrivateProfileIntA(LPCSTR lpAppName, LPCSTR lpKeyName, INT nDefault, LPCSTR lpFileName);
// DWORD __stdcall GetPrivateProfileStringA(LPCSTR lpAppName, LPCSTR lpKeyName, LPCSTR lpDefault, LPSTR lpReturnedString, DWORD nSize, LPCSTR lpFileName);
// char *__cdecl _itoa(int Value, char *Buffer, int Radix);
// void __stdcall Sleep(DWORD dwMilliseconds);

//-------------------------------------------------------------------------
// Data declarations

const _ThrowInfo _TI1I = { 0u, &SeTranslator, &SeTranslator, &_CTA1I }; // idb
void *Crwini::`vftable' = &Crwini::`vector deleting destructor'; // weak


//----- (00000000) --------------------------------------------------------
void __cdecl __noreturn SeTranslator(unsigned int pExceptionObject)
{
  _CxxThrowException(&pExceptionObject, (_ThrowInfo *)&_TI1I);
}

//----- (00000060) --------------------------------------------------------
Crwini *__thiscall Crwini::Crwini(Crwini *this)
{
  Crwini *result; // eax

  result = this;
  *(_DWORD *)this = &Crwini::`vftable';
  return result;
}
// 70: using guessed type void *Crwini::`vftable';

//----- (00000074) --------------------------------------------------------
Crwini *__thiscall Crwini::`scalar deleting destructor'(Crwini *this, char a2)
{
  Crwini::~Crwini(this);
  if ( (a2 & 1) != 0 )
    operator delete(this);
  return this;
}

//----- (00000094) --------------------------------------------------------
void __thiscall Crwini::~Crwini(Crwini *this)
{
  *(_DWORD *)this = &Crwini::`vftable';
}
// 70: using guessed type void *Crwini::`vftable';

//----- (000000A4) --------------------------------------------------------
char __thiscall Crwini::WriteString(Crwini *this, LPCSTR lpAppName, LPCSTR lpKeyName, LPCSTR lpString, char *a5)
{
  CHAR Filename[256]; // [esp+Ch] [ebp-100h] BYREF

  GetModuleFileNameA(0, Filename, 0xFFu);
  strrchr(Filename, 92)[1] = 0;
  strcat(Filename, a5);
  WritePrivateProfileStringA(lpAppName, lpKeyName, lpString, Filename);
  return 1;
}

//----- (00000134) --------------------------------------------------------
UINT __thiscall Crwini::GetInt(Crwini *this, LPCSTR lpAppName, LPCSTR lpKeyName, char *a4)
{
  CHAR Filename[256]; // [esp+Ch] [ebp-100h] BYREF

  GetModuleFileNameA(0, Filename, 0xFFu);
  strrchr(Filename, 92)[1] = 0;
  strcat(Filename, a4);
  return GetPrivateProfileIntA(lpAppName, lpKeyName, 1, Filename);
}

//----- (000001C4) --------------------------------------------------------
void __thiscall Crwini::ReadString(Crwini *this, LPCSTR lpAppName, LPCSTR lpKeyName, char *a4, char *const lpReturnedString)
{
  CHAR Filename[256]; // [esp+Ch] [ebp-100h] BYREF

  GetModuleFileNameA(0, Filename, 0xFFu);
  strrchr(Filename, 92)[1] = 0;
  strcat(Filename, a4);
  GetPrivateProfileStringA(lpAppName, lpKeyName, 0, lpReturnedString, 0xFFu, Filename);
}

//----- (00000264) --------------------------------------------------------
void __thiscall Crwini::WriteInt(Crwini *this, LPCSTR lpKeyName, LPCSTR lpAppName, char *a4, int Value)
{
  char Buffer[12]; // [esp+Ch] [ebp-10Ch] BYREF
  CHAR Filename[256]; // [esp+18h] [ebp-100h] BYREF

  GetModuleFileNameA(0, Filename, 0xFFu);
  strrchr(Filename, 92)[1] = 0;
  strcat(Filename, a4);
  _itoa(Value, Buffer, 10);
  WritePrivateProfileStringA(lpAppName, lpKeyName, Buffer, Filename);
}

//----- (00000304) --------------------------------------------------------
void __cdecl DBSleep(DWORD dwMilliseconds)
{
  DWORD v1; // eax

  v1 = dwMilliseconds;
  if ( (int)dwMilliseconds > 100 )
    v1 = 100;
  Sleep(v1);
}

// nfuncs=18 queued=9 decompiled=9 lumina nreq=0 worse=0 better=0
// ALL OK, 9 function(s) have been successfully decompiled
